In [2]:
import csv
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [3]:
df= pd.read_csv('data/transcription.csv')

In [4]:
df.head()

,Transcriber,Block #,Parcel #,Ward #,Box #,Street number,Street address,Land use,Previous Transfer of deed Event Date,Previous Transfer of deed People Involved,...,Decision People Involved,Decision Role,Award Date,Award Amount Money,Tenant Vacated Date,Tenant Agreement Date,Tenant Cost,Tenant Name,Previous owner or Tenant,End of Case Finalized Date
0,NaN,1,2,4,56,198\n198 1/2\n198-200,Hillard Ave.,Commercial,-,Bessie S. Kalogerakis\n\nAmelia K. Kalogerakis...,...,\nAmelia K. Kalogerakis\nEva K. Cleraderas\nSt...,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,06/06/1969
1,NaN,1,3,4,56,202-208,Hillard Ave.,Commercial,08/01/1967,W.S. Harrison\nBeulah L. Harrison\n\nCharles R...,...,"Charles R. Stinnette Co., Inc.\n\nHACA",Owner\n\nPurchaser,07/16/1971,21600,-,-,-,-,-,06/171971
2,NaN,1,4,4,56,90\n196,Asheland Ave.\nHillard Ave.,Commercial,04/04/1940,"Charles G. Lee, Sr.\n\nCharles G. Lee, Jr.\nH....",...,William I. Lee\nZyphin J. Lee\nH. Kenneth Lee\...,Owner\n\n\n\nPurchaser,08/17/1972,46000,-,-,-,-,-,07/13/1972
3,NaN,1,5,4,56,94,Asheland Ave.,Residential,04/28/1934,John E. Smathers\nEtta C. Smathers\n\nThelma S...,...,Thelma Smathers Johnson\nElizabeth Pauline Sma...,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,05/29/1974
4,NaN,1,6,4,56,98,Asheland Ave.,Commercial,12/24/1964,C.A. Yarbrough\nSarah M Yarbrough\n\nHarry's C...,...,"Harry's Cadillac-Pontiac Company, Inc.\n\nHACA\n",Owner\n\nPurchaser,-,-,-,-,-,-,-,10/09/1974

In [5]:
copy=df
copy.head()

,Transcriber,Block #,Parcel #,Ward #,Box #,Street number,Street address,Land use,Previous Transfer of deed Event Date,Previous Transfer of deed People Involved,...,Decision People Involved,Decision Role,Award Date,Award Amount Money,Tenant Vacated Date,Tenant Agreement Date,Tenant Cost,Tenant Name,Previous owner or Tenant,End of Case Finalized Date
0,NaN,1,2,4,56,198\n198 1/2\n198-200,Hillard Ave.,Commercial,-,Bessie S. Kalogerakis\n\nAmelia K. Kalogerakis...,...,\nAmelia K. Kalogerakis\nEva K. Cleraderas\nSt...,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,06/06/1969
1,NaN,1,3,4,56,202-208,Hillard Ave.,Commercial,08/01/1967,W.S. Harrison\nBeulah L. Harrison\n\nCharles R...,...,"Charles R. Stinnette Co., Inc.\n\nHACA",Owner\n\nPurchaser,07/16/1971,21600,-,-,-,-,-,06/171971
2,NaN,1,4,4,56,90\n196,Asheland Ave.\nHillard Ave.,Commercial,04/04/1940,"Charles G. Lee, Sr.\n\nCharles G. Lee, Jr.\nH....",...,William I. Lee\nZyphin J. Lee\nH. Kenneth Lee\...,Owner\n\n\n\nPurchaser,08/17/1972,46000,-,-,-,-,-,07/13/1972
3,NaN,1,5,4,56,94,Asheland Ave.,Residential,04/28/1934,John E. Smathers\nEtta C. Smathers\n\nThelma S...,...,Thelma Smathers Johnson\nElizabeth Pauline Sma...,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,05/29/1974
4,NaN,1,6,4,56,98,Asheland Ave.,Commercial,12/24/1964,C.A. Yarbrough\nSarah M Yarbrough\n\nHarry's C...,...,"Harry's Cadillac-Pontiac Company, Inc.\n\nHACA\n",Owner\n\nPurchaser,-,-,-,-,-,-,-,10/09/1974

In [6]:
copy.drop(['Transcriber'], axis=1, inplace=True)

In [7]:
copy.head()

,Block #,Parcel #,Ward #,Box #,Street number,Street address,Land use,Previous Transfer of deed Event Date,Previous Transfer of deed People Involved,Previous Transfer of deed Role,...,Decision People Involved,Decision Role,Award Date,Award Amount Money,Tenant Vacated Date,Tenant Agreement Date,Tenant Cost,Tenant Name,Previous owner or Tenant,End of Case Finalized Date
0,1,2,4,56,198\n198 1/2\n198-200,Hillard Ave.,Commercial,-,Bessie S. Kalogerakis\n\nAmelia K. Kalogerakis...,Owner\n\n\n\nHeir,...,\nAmelia K. Kalogerakis\nEva K. Cleraderas\nSt...,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,06/06/1969
1,1,3,4,56,202-208,Hillard Ave.,Commercial,08/01/1967,W.S. Harrison\nBeulah L. Harrison\n\nCharles R...,Owner\n\n\nPurchaser,...,"Charles R. Stinnette Co., Inc.\n\nHACA",Owner\n\nPurchaser,07/16/1971,21600,-,-,-,-,-,06/171971
2,1,4,4,56,90\n196,Asheland Ave.\nHillard Ave.,Commercial,04/04/1940,"Charles G. Lee, Sr.\n\nCharles G. Lee, Jr.\nH....",Owner\n\n\nHeir,...,William I. Lee\nZyphin J. Lee\nH. Kenneth Lee\...,Owner\n\n\n\nPurchaser,08/17/1972,46000,-,-,-,-,-,07/13/1972
3,1,5,4,56,94,Asheland Ave.,Residential,04/28/1934,John E. Smathers\nEtta C. Smathers\n\nThelma S...,Owner\n\n\nHeir,...,Thelma Smathers Johnson\nElizabeth Pauline Sma...,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,05/29/1974
4,1,6,4,56,98,Asheland Ave.,Commercial,12/24/1964,C.A. Yarbrough\nSarah M Yarbrough\n\nHarry's C...,Owner\n\nPurchaser,...,"Harry's Cadillac-Pontiac Company, Inc.\n\nHACA\n",Owner\n\nPurchaser,-,-,-,-,-,-,-,10/09/1974

In [8]:
copy=copy[copy['Block #'].str.contains("Spring")==False]

In [9]:
parcels=df[['Block #', 'Parcel #','Ward #','Land use']]

In [10]:
parcels=parcels[parcels['Block #'].str.contains("Spring")==False]

In [11]:
parcels=parcels[parcels['Block #'].str.contains("  ")==False]

In [12]:
parcels['Block #'].dtypes

dtype('O')

In [13]:
parcels.insert(0, 'Parcel_ID', range(0,0+len(parcels)))

In [14]:
parcels.head()

   Parcel_ID Block # Parcel # Ward #     Land use
0          0       1        2      4   Commercial
1          1       1        3      4   Commercial
2          2       1        4      4   Commercial
3          3       1        5      4  Residential
4          4       1        6      4   Commercial

In [14]:
parcels.to_csv('Parcels.csv')

In [15]:
parcels. shape

(542, 5)

In [16]:
parcel_id=parcels[['Parcel_ID']]

In [17]:
addresses= copy[['Street number', 'Street address']]

In [18]:
addresses=addresses.join(parcels[['Parcel_ID']])

In [19]:
addresses.head()

           Street number               Street address  Parcel_ID
0  198\n198 1/2\n198-200                 Hillard Ave.          0
1                202-208                 Hillard Ave.          1
2                90\n196  Asheland Ave.\nHillard Ave.          2
3                     94                Asheland Ave.          3
4                     98                Asheland Ave.          4

In [24]:
addresses.shape

(542, 3)

In [25]:
addresses.head()

           Street number               Street address  Parcel_ID
0  198\n198 1/2\n198-200                 Hillard Ave.          0
1                202-208                 Hillard Ave.          1
2                90\n196  Asheland Ave.\nHillard Ave.          2
3                     94                Asheland Ave.          3
4                     98                Asheland Ave.          4

In [26]:
test= splitRow(addresses)
test
##s = test[test['Street address'] == 'Hillard Ave.']
##x = addresses[addresses['Street address'] == 'Hillard Ave.']
##print(x)

NameError: name 'splitRow' is not defined

In [27]:
test.insert(0,'ID',range(0,0+len(test)))

NameError: name 'test' is not defined

In [28]:
test.head()

NameError: name 'test' is not defined

In [29]:
test.to_csv('addresses.csv')

NameError: name 'test' is not defined

In [30]:
def splitRow(table):
    newframe=pd.DataFrame(columns=table.columns.values)
    size=0
    for i in range(len(table)):
        row = table.iloc[i]
        if '\n' in str(row['Street number']):
            data = row['Street number'].split('\n')
            for d in data:
                newrow = row
                newrow['Street number'] = d
                newframe.loc[size]=newrow
                size+=1
        else:
            newframe.loc[size]=row
            size+=1
    return newframe

In [31]:
test.t

NameError: name 'test' is not defined

In [32]:
people=copy[['Previous Transfer of deed People Involved','Decision People Involved']]

In [33]:
def splitRowTransfer(table):
    newframe=pd.DataFrame(columns=table.columns.values)
    size=0
    for i in range(len(table)):
        row = table.iloc[i]
        if '\n' in str(row['Previous Transfer of deed People Involved']):
            data = row['Previous Transfer of deed People Involved'].split('\n')
            for d in data:
                newrow = row
                newrow['Previous Transfer of deed People Involved'] = d
                newframe.loc[size]=newrow
                size+=1
        else:
            newframe.loc[size]=row
            size+=1
    return newframe

In [34]:
transfer=splitRowTransfer(people)

In [35]:
transfer.drop('Decision People Involved', axis=1, inplace=True)

In [36]:
transfer['Previous Transfer of deed People Involved'].replace('', np.nan, inplace=True)

In [37]:
transfer.dropna(inplace=True)

In [38]:
transfer

     Previous Transfer of deed People Involved
0                        Bessie S. Kalogerakis
2                        Amelia K. Kalogerakis
3                            Eva K. Cleraderas
4                            Steve Kalogerakis
5                                W.S. Harrison
6                           Beulah L. Harrison
8               Charles R. Stinnette Co., Inc.
9                          Charles G. Lee, Sr.
11                         Charles G. Lee, Jr.
12                               H. Keneth Lee
13                            John E. Smathers
14                            Etta C. Smathers
16                     Thelma Smathers Johnson
17                              C.A. Yarbrough
18                           Sarah M Yarbrough
20      Harry's Cadillac-Pontiac Company, Inc.
21                                Z. K. Morgan
22                           Shirley P. Morgan
23                               J. D. Medling
24                            Leila P. Medling
26                               Max E. Wilson
27                             Flora J. Wilson
28                                Z. K. Morgan
29                           Shirley P. Morgan
30                               J. D. Medling
31                            Leila P. Medling
33                 Grayson Huntzberger Fleming
34                        Peggy Evelyn Fleming
35                                 K. F. Wentz
36                             Tennie D. Clark
...                                        ...
2290                        Louise Cliff Crews
2291                 First Union National Bank
2292                            D. B. McKenzie
2294                   J.G. Stike-leather, Jr.
2295                     Dorothy Stike-leather
2297                             Max E. Wilson
2298                             H. E. Garrett
2300                           Charles G. Buck
2301                           Nell P. Garrett
2302                          Estelle B. Smith
2304                             Fred Barnette
2305                    Marguerita W. Thompson
2307                               W.T. Conley
2308                           Mary Lou Conley
2309                                E Zaph Ray
2310                                 Mary Carr
2312                         August J Erickson
2313                           Mary L Erickson
2314                    Claude Marion Creasman
2316                             Myrdirth Owen
2317                    Claude Marion Creasman
2319                             Myrdirth Owen
2320                    Claude Marion Creasman
2322                             Myrdirth Owen
2323                    Sandra Olivia Nicholas
2325                      Zipporah L. Nicholas
2326                    Sandra Olivia Nicholas
2328                      Zipporah L. Nicholas
2329                    Sandra Olivia Nicholas
2331                      Zipporah L. Nicholas

[1749 rows x 1 columns]

In [39]:
people=copy[['Previous Transfer of deed People Involved','Decision People Involved']]

In [40]:
def splitRowDecisions(table):
    newframe=pd.DataFrame(columns=table.columns.values)
    size=0
    for i in range(len(table)):
        row = table.iloc[i]
        if '\n' in str(row['Decision People Involved']):
            data = row['Decision People Involved'].split('\n')
            for d in data:
                newrow = row
                newrow['Decision People Involved'] = d
                newframe.loc[size]=newrow
                size+=1
        else:
            newframe.loc[size]=row
            size+=1
    return newframe

In [41]:
decisions= splitRowDecisions(people)

In [42]:
decisions.drop('Previous Transfer of deed People Involved', axis=1, inplace=True)

In [43]:
decisions['Decision People Involved'].replace('', np.nan, inplace=True)

In [44]:
decisions.dropna(inplace=True)

In [45]:
decisions

                    Decision People Involved
1                      Amelia K. Kalogerakis
2                          Eva K. Cleraderas
3                          Steve Kalogerakis
5                                       HACA
6             Charles R. Stinnette Co., Inc.
8                                       HACA
9                             William I. Lee
10                             Zyphin J. Lee
11                            H. Kenneth Lee
12                            Frances W. Lee
14                                      HACA
15                   Thelma Smathers Johnson
16                Elizabeth Pauline Smathers
18                                      HACA
19    Harry's Cadillac-Pontiac Company, Inc.
21                                      HACA
23                             Max E. Wilson
24                           Flora J. Wilson
25                             J. D. Medling
27                                      HACA
28               Grayson Huntzberger Fleming
29                      Peggy Evelyn Fleming
31                                      HACA
32                       Luther Earl McCurry
33                         Maxine S. McCurry
35                                      HACA
36                         William J. Reeves
37                         Mildred P. Reeves
39                                      HACA
40                      Millco, Incorporated
...                                      ...
1807                          Perle T. Cliff
1808                         Horace A. Cliff
1809                   Lora Lee Morris Cliff
1810                        Charles J. Cliff
1811                       Betty Young Cliff
1812                     Louise Cliff Cruise
1813                            R. R. Cruise
1814                 Ruth Mary Cliff Helfand
1815                           W. T. Helfand
1817                                    HACA
1818                           Max E. Wilson
1819                         Flora J. Wilson
1821                                    HACA
1822                         Charles G. Buck
1823                         Nell P. Garrett
1825                                    HACA
1826                            Fred Barnard
1827                         Roselyn Barnard
1829                                    HACA
1830                                       -
1833                    Myrdirth Owen Howell
1835                                    HACA
1836                    Myrdirth Owen Howell
1838                                    HACA
1839                       Zipporah Nicholas
1841                                    HACA
1842                       Zipporah Nicholas
1844                                    HACA
1845                       Zipporah Nicholas
1847                                    HACA

[1298 rows x 1 columns]

In [46]:
def combined(df1,df2):
    newdf=pd.DataFrame(columns=['People'])
    size=0
    for i in range(len(df1)):
        row=df1.iloc[i]
        data = row['Previous Transfer of deed People Involved']
        newdf.loc[size]=data
        size+=1
    for y in range(len(df2)):
        row=df2.iloc[y]
        data = row['Decision People Involved']
        newdf.loc[size]=data
        size+=1
    return newdf

In [47]:
allPeople=combined(transfer,decisions)

In [48]:
allPeople=allPeople.drop_duplicates(subset='People', keep="first")

In [49]:
allPeople

                                                 People
0                                 Bessie S. Kalogerakis
1                                 Amelia K. Kalogerakis
2                                     Eva K. Cleraderas
3                                     Steve Kalogerakis
4                                         W.S. Harrison
5                                    Beulah L. Harrison
6                        Charles R. Stinnette Co., Inc.
7                                   Charles G. Lee, Sr.
8                                   Charles G. Lee, Jr.
9                                         H. Keneth Lee
10                                     John E. Smathers
11                                     Etta C. Smathers
12                              Thelma Smathers Johnson
13                                       C.A. Yarbrough
14                                    Sarah M Yarbrough
15               Harry's Cadillac-Pontiac Company, Inc.
16                                         Z. K. Morgan
17                                    Shirley P. Morgan
18                                        J. D. Medling
19                                     Leila P. Medling
20                                        Max E. Wilson
21                                      Flora J. Wilson
26                          Grayson Huntzberger Fleming
27                                 Peggy Evelyn Fleming
28                                          K. F. Wentz
29                                      Tennie D. Clark
30                                         Herman Clark
31                                       Marie M. Clark
32                                           Paul Clark
33                                        Minnie Clark
...                                                 ...
2952                        Thomas J. Parks (unmarried)
2961                              P. Greer Johnson Jr.
2964                                    Ruth G. Wilson
2966                                      David K. Hall
2979                                       R. W. Willis
2988                                      Fred Pearlman
2989                                   Anne M. Pearlman
2991                                 Roxie Holden Queen
2992                                        Gleen Queen
2999                                      VIrginia York
3004  Fire Baptized Holiness Church of God of the Am...
3005         Adam Caldwell, Fannie Gardenhight, et. al.
3007                       Adeline Cole (formerly Cole)
3010  Redevelopment Commission of the City of Asheville
3012                                  Patricia Ann King
3015                                        W.K. Morris
3016                                      Jack B. Cliff
3017                                     Perle T. Cliff
3018                                    Horace A. Cliff
3019                              Lora Lee Morris Cliff
3020                                   Charles J. Cliff
3021                                  Betty Young Cliff
3022                                Louise Cliff Cruise
3023                                       R. R. Cruise
3024                            Ruth Mary Cliff Helfand
3025                                      W. T. Helfand
3033                                       Fred Barnard
3034                                    Roselyn Barnard
3037                               Myrdirth Owen Howell
3041                                  Zipporah Nicholas

[1792 rows x 1 columns]

In [50]:
allPeople.insert(0, 'Person_ID', range(0,0+len(allPeople)))

In [51]:
allPeople.to_csv('People.csv')

In [52]:
copy.head()

,Block #,Parcel #,Ward #,Box #,Street number,Street address,Land use,Previous Transfer of deed Event Date,Previous Transfer of deed People Involved,Previous Transfer of deed Role,...,Decision People Involved,Decision Role,Award Date,Award Amount Money,Tenant Vacated Date,Tenant Agreement Date,Tenant Cost,Tenant Name,Previous owner or Tenant,End of Case Finalized Date
0,1,2,4,56,198\n198 1/2\n198-200,Hillard Ave.,Commercial,-,Bessie S. Kalogerakis\n\nAmelia K. Kalogerakis...,Owner\n\n\n\nHeir,...,\nAmelia K. Kalogerakis\nEva K. Cleraderas\nSt...,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,06/06/1969
1,1,3,4,56,202-208,Hillard Ave.,Commercial,08/01/1967,W.S. Harrison\nBeulah L. Harrison\n\nCharles R...,Owner\n\n\nPurchaser,...,"Charles R. Stinnette Co., Inc.\n\nHACA",Owner\n\nPurchaser,07/16/1971,21600,-,-,-,-,-,06/171971
2,1,4,4,56,90\n196,Asheland Ave.\nHillard Ave.,Commercial,04/04/1940,"Charles G. Lee, Sr.\n\nCharles G. Lee, Jr.\nH....",Owner\n\n\nHeir,...,William I. Lee\nZyphin J. Lee\nH. Kenneth Lee\...,Owner\n\n\n\nPurchaser,08/17/1972,46000,-,-,-,-,-,07/13/1972
3,1,5,4,56,94,Asheland Ave.,Residential,04/28/1934,John E. Smathers\nEtta C. Smathers\n\nThelma S...,Owner\n\n\nHeir,...,Thelma Smathers Johnson\nElizabeth Pauline Sma...,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,05/29/1974
4,1,6,4,56,98,Asheland Ave.,Commercial,12/24/1964,C.A. Yarbrough\nSarah M Yarbrough\n\nHarry's C...,Owner\n\nPurchaser,...,"Harry's Cadillac-Pontiac Company, Inc.\n\nHACA\n",Owner\n\nPurchaser,-,-,-,-,-,-,-,10/09/1974

In [53]:
allPeople=allPeople.apply(lambda x: x.astype(str).str.lower())

In [54]:
allPeople.head()

  Person_ID                 People
0         0  bessie s. kalogerakis
1         1  amelia k. kalogerakis
2         2      eva k. cleraderas
3         3      steve kalogerakis
4         4          w.s. harrison

In [55]:
allPeople=allPeople.drop_duplicates(subset='People', keep="first")

In [56]:
allPeople.shape

(1787, 2)

In [57]:
allPeople.drop('Person_ID', axis=1, inplace=True)

In [58]:
allPeople.insert(0, 'Person_ID', range(0,0+len(allPeople)))

In [59]:
allPeople.head()

   Person_ID                 People
0          0  bessie s. kalogerakis
1          1  amelia k. kalogerakis
2          2      eva k. cleraderas
3          3      steve kalogerakis
4          4          w.s. harrison

In [60]:
allPeople.to_csv('People.csv')

In [162]:
event_assoc=copy[['Decision People Involved','Decision Role']]

In [163]:
event_assoc

,Decision People Involved,Decision Role
0,\nAmelia K. Kalogerakis\nEva K. Cleraderas\nSt...,Owner\n\n\nPurchaser
1,"Charles R. Stinnette Co., Inc.\n\nHACA",Owner\n\nPurchaser
2,William I. Lee\nZyphin J. Lee\nH. Kenneth Lee\...,Owner\n\n\n\nPurchaser
3,Thelma Smathers Johnson\nElizabeth Pauline Sma...,Owner\n\n\nPurchaser
4,"Harry's Cadillac-Pontiac Company, Inc.\n\nHACA\n",Owner\n\nPurchaser
5,Max E. Wilson\nFlora J. Wilson\nJ. D. Medling\...,Owner\n\n\n\nPurchaser
6,Grayson Huntzberger Fleming\nPeggy Evelyn Flem...,Owner\n\n\nPurchaser
7,Luther Earl McCurry\nMaxine S. McCurry\n\nHACA,Owner\n\n\nPurchaser
8,William J. Reeves\nMildred P. Reeves\n\nHACA,Owner\n\n\nPurchaser
9,"Millco, Incorporated\nM. O. Causey\n\nHACA",Owner\n\n\nPurchaser
10,J. A. Reyes\n\nHACA,Owner\n\nPurchaser
11,Charles McGowan\n\nHACA,Owner\n\nPurchaser
12,Charles McGowan\n\nHACA,Owner\n\nPurchaser
13,John F. Shuford\nWachovia Bank and Trust Compa...,Owner\nTrustee\n\nPurchaser
14,Rudolph Gay\n\nHACA,Owner\n\nPurchaser
15,Raymond McCorkle\nMarie McCorkle\n\nHACA,Heirs\n\nPurchaser
16,Ada Barnard\n\nHACA,Owner\n\nPurchaser
17,Herman Fleming\n\nHACA,Owner \n\nPurchaser
18,Genuine Parts Company\n\nHACA,Owner \n\nPurchaser
19,Mildred L. Messer\n\nHACA,Owner \n\nPurchaser
20,Thomas F. Ruth\nAnne McConnel Ruth\n\nHACA,Owner \n\nPurchaser
21,Ruben J. Dailey\n(Administrator of the Estate ...,Trustee\n\n\n\nPurchaser
22,Josephine Beam\nAlfred Beam\n\nHACA,Owner \n\nPurchaser
23,Cora J. Shuford\n\nHACA,Owner \n\nPurchaser
24,NaN,NaN
25,NaN,NaN
26,NaN,NaN
27,Maizei Clark Williams\n\nHACA,Owner\n\nPurchaser
28,Mazie Williams\n\nHACA,Owner\n\nPurchaser\n
29,Etta Lynch\nPauline P. Hood\n\nHACA\n,Heirs\n\nPurchaser
...,...,...
525,-,-
526,-,-
527,-,-
528,Fred Pearlman\nAnne M. Pearlman\n\nHACA,Owner\n\n\nPurchaser
529,Roxie Holden Queen\nGleen Queen\n\nHACA,Owner\n\n\nPurchaser
530,NaN,NaN
531,NaN,NaN
532,Marshall Logan\nGladys Logan\n\nHACA,Owner\n\n\nPurchaser
533,Lessie K. Angel\n\nHACA,Owner\n\nPurchaser
534,VIrginia York\n\nHACA,Owner\n\nPurchaser
535,Henry Maddox\nManor Lee Maddox\n\nHACA,Owner\n\nPurchaser
536,Fire Baptized Holiness Church of God of the Am...,Owner\n\nPurchaser
537,NaN,NaN
538,NaN,NaN
539,Adeline Cole (formerly Cole)\n\nHACA,Owner\n\n\nPurchaser
540,Katherine Gardner\n\nRedevelopment Commission ...,Owner\n\nPurchaser
541,NaN,NaN
542,James Edward King\nPatricia Ann King\n\nRedeve...,Owner\n\nPurchaser
543,Julia Cliff Morris\nW.K. Morris\nJack B. Cliff...,Owner\n\nPurchaser
544,Max E. Wilson\nFlora J. Wilson\n\nHACA,Owner\n\nPurchaser
545,Charles G. Buck\nNell P. Garrett\n\nHACA,Trustee\n\nPurchaser
546,Fred Barnard\nRoselyn Barnard\n\nHACA,Owner\n\nPurchaser
547,-,-
549,NaN,NaN
550,NaN,NaN
551,Myrdirth Owen Howell\n\nHACA,owner\n\npurchaser
552,Myrdirth Owen Howell\n\nHACA,Owner\n\npurchaser
553,Zipporah Nicholas\n\nHACA,owner\n\npurchaser
554,Zipporah Nicholas\n\nHACA,owner\n\npurchaser
555,Zipporah Nicholas\n\nHACA,owner\n\npurchaser

In [164]:
def splitRowEvents(table):
    newframe=pd.DataFrame(columns=table.columns.values)
    size=0
    for i in range(len(table)):
        row = table.iloc[i]
        if '\n' in str(row['Decision People Involved']):
            data = row['Decision People Involved'].split('\n')
            norm='Owner'
            norm_prev='Owner'
            norm2='Purchaser'
            for d in range(len(data)):
                newrow = row
                newrow['Decision People Involved'] = data[d]
                if data[d]!='':
                    newrow['Decision Role']=norm_prev
                if data[d]=='':
                    if norm_prev==norm:
                        norm_prev=norm2
                    else:
                        norm_prev=norm
                        
        
                newframe.loc[size]=newrow
                size+=1
        else:
            newframe.loc[size]=row
            size+=1
    return newframe

In [165]:
t=splitRowEvents(event_assoc)

In [166]:
t

                    Decision People Involved         Decision Role
0                                             Owner\n\n\nPurchaser
1                      Amelia K. Kalogerakis             Purchaser
2                          Eva K. Cleraderas             Purchaser
3                          Steve Kalogerakis             Purchaser
4                                                        Purchaser
5                                       HACA                 Owner
6             Charles R. Stinnette Co., Inc.                 Owner
7                                                            Owner
8                                       HACA             Purchaser
9                             William I. Lee                 Owner
10                             Zyphin J. Lee                 Owner
11                            H. Kenneth Lee                 Owner
12                            Frances W. Lee                 Owner
13                                                           Owner
14                                      HACA             Purchaser
15                   Thelma Smathers Johnson                 Owner
16                Elizabeth Pauline Smathers                 Owner
17                                                           Owner
18                                      HACA             Purchaser
19    Harry's Cadillac-Pontiac Company, Inc.                 Owner
20                                                           Owner
21                                      HACA             Purchaser
22                                                       Purchaser
23                             Max E. Wilson                 Owner
24                           Flora J. Wilson                 Owner
25                             J. D. Medling                 Owner
26                                                           Owner
27                                      HACA             Purchaser
28               Grayson Huntzberger Fleming                 Owner
29                      Peggy Evelyn Fleming                 Owner
...                                      ...                   ...
1818                           Max E. Wilson                 Owner
1819                         Flora J. Wilson                 Owner
1820                                                         Owner
1821                                    HACA             Purchaser
1822                         Charles G. Buck                 Owner
1823                         Nell P. Garrett                 Owner
1824                                                         Owner
1825                                    HACA             Purchaser
1826                            Fred Barnard                 Owner
1827                         Roselyn Barnard                 Owner
1828                                                         Owner
1829                                    HACA             Purchaser
1830                                       -                     -
1831                                     NaN                   NaN
1832                                     NaN                   NaN
1833                    Myrdirth Owen Howell                 Owner
1834                                                         Owner
1835                                    HACA             Purchaser
1836                    Myrdirth Owen Howell                 Owner
1837                                                         Owner
1838                                    HACA             Purchaser
1839                       Zipporah Nicholas                 Owner
1840                                                         Owner
1841                                    HACA             Purchaser
1842                       Zipporah Nicholas                 Owner
1843                                                         Owner
1844                                    HACA             Purchaser
1845                       Zipporah Nicholas                 Owner
1846                                                         Owner
1847                                    HACA             Purchaser

[1848 rows x 2 columns]

In [167]:
t['Decision People Involved'].replace('', np.nan, inplace=True)
t

                    Decision People Involved         Decision Role
0                                        NaN  Owner\n\n\nPurchaser
1                      Amelia K. Kalogerakis             Purchaser
2                          Eva K. Cleraderas             Purchaser
3                          Steve Kalogerakis             Purchaser
4                                        NaN             Purchaser
5                                       HACA                 Owner
6             Charles R. Stinnette Co., Inc.                 Owner
7                                        NaN                 Owner
8                                       HACA             Purchaser
9                             William I. Lee                 Owner
10                             Zyphin J. Lee                 Owner
11                            H. Kenneth Lee                 Owner
12                            Frances W. Lee                 Owner
13                                       NaN                 Owner
14                                      HACA             Purchaser
15                   Thelma Smathers Johnson                 Owner
16                Elizabeth Pauline Smathers                 Owner
17                                       NaN                 Owner
18                                      HACA             Purchaser
19    Harry's Cadillac-Pontiac Company, Inc.                 Owner
20                                       NaN                 Owner
21                                      HACA             Purchaser
22                                       NaN             Purchaser
23                             Max E. Wilson                 Owner
24                           Flora J. Wilson                 Owner
25                             J. D. Medling                 Owner
26                                       NaN                 Owner
27                                      HACA             Purchaser
28               Grayson Huntzberger Fleming                 Owner
29                      Peggy Evelyn Fleming                 Owner
...                                      ...                   ...
1818                           Max E. Wilson                 Owner
1819                         Flora J. Wilson                 Owner
1820                                     NaN                 Owner
1821                                    HACA             Purchaser
1822                         Charles G. Buck                 Owner
1823                         Nell P. Garrett                 Owner
1824                                     NaN                 Owner
1825                                    HACA             Purchaser
1826                            Fred Barnard                 Owner
1827                         Roselyn Barnard                 Owner
1828                                     NaN                 Owner
1829                                    HACA             Purchaser
1830                                       -                     -
1831                                     NaN                   NaN
1832                                     NaN                   NaN
1833                    Myrdirth Owen Howell                 Owner
1834                                     NaN                 Owner
1835                                    HACA             Purchaser
1836                    Myrdirth Owen Howell                 Owner
1837                                     NaN                 Owner
1838                                    HACA             Purchaser
1839                       Zipporah Nicholas                 Owner
1840                                     NaN                 Owner
1841                                    HACA             Purchaser
1842                       Zipporah Nicholas                 Owner
1843                                     NaN                 Owner
1844                                    HACA             Purchaser
1845                       Zipporah Nicholas                 Owner
1846                                     NaN                 Owner
1847                                    HACA             Purchaser

[1848 rows x 2 columns]

In [169]:
t.dropna(inplace=True)

In [169]:
t.merge

In [169]:
allPeople.insert(0, 'Event_ID', range(0,0+len(allPeople)))

In [171]:
t.to_csv('Event_People_Association.csv')

In [15]:
copy

,Block #,Parcel #,Ward #,Box #,Street number,Street address,Land use,Previous Transfer of deed Event Date,Previous Transfer of deed People Involved,Previous Transfer of deed Role,...,Decision People Involved,Decision Role,Award Date,Award Amount Money,Tenant Vacated Date,Tenant Agreement Date,Tenant Cost,Tenant Name,Previous owner or Tenant,End of Case Finalized Date
0,1,2,4,56,198\n198 1/2\n198-200,Hillard Ave.,Commercial,-,Bessie S. Kalogerakis\n\nAmelia K. Kalogerakis...,Owner\n\n\n\nHeir,...,\nAmelia K. Kalogerakis\nEva K. Cleraderas\nSt...,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,06/06/1969
1,1,3,4,56,202-208,Hillard Ave.,Commercial,08/01/1967,W.S. Harrison\nBeulah L. Harrison\n\nCharles R...,Owner\n\n\nPurchaser,...,"Charles R. Stinnette Co., Inc.\n\nHACA",Owner\n\nPurchaser,07/16/1971,21600,-,-,-,-,-,06/171971
2,1,4,4,56,90\n196,Asheland Ave.\nHillard Ave.,Commercial,04/04/1940,"Charles G. Lee, Sr.\n\nCharles G. Lee, Jr.\nH....",Owner\n\n\nHeir,...,William I. Lee\nZyphin J. Lee\nH. Kenneth Lee\...,Owner\n\n\n\nPurchaser,08/17/1972,46000,-,-,-,-,-,07/13/1972
3,1,5,4,56,94,Asheland Ave.,Residential,04/28/1934,John E. Smathers\nEtta C. Smathers\n\nThelma S...,Owner\n\n\nHeir,...,Thelma Smathers Johnson\nElizabeth Pauline Sma...,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,05/29/1974
4,1,6,4,56,98,Asheland Ave.,Commercial,12/24/1964,C.A. Yarbrough\nSarah M Yarbrough\n\nHarry's C...,Owner\n\nPurchaser,...,"Harry's Cadillac-Pontiac Company, Inc.\n\nHACA\n",Owner\n\nPurchaser,-,-,-,-,-,-,-,10/09/1974
5,1,7,4,56,110 - 112,Asheland Ave.,Commercial,04/03/1964,Z. K. Morgan\nShirley P. Morgan\nJ. D. Medling...,Owner\n\n\n\n\nPurchaser,...,Max E. Wilson\nFlora J. Wilson\nJ. D. Medling\...,Owner\n\n\n\nPurchaser,04/02/1976,60000,-,-,-,-,-,04/12/1976
6,1,8,4,56,114,Asheland Ave.,Residential,08/22/1958,Z. K. Morgan\nShirley P. Morgan\nJ. D. Medling...,Owner\n\n\n\n\nPurchaser,...,Grayson Huntzberger Fleming\nPeggy Evelyn Flem...,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,12/09/1969
7,1,9,4,56,122,Asheland Ave.,Commercial,01/06/1955,K. F. Wentz\nTennie D. Clark\nHerman Clark\nMa...,Owner\n\n\n\n\n\n\n\n\n\n\n\n\nPurchaser,...,Luther Earl McCurry\nMaxine S. McCurry\n\nHACA,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,09/26/1969
8,1,10,4,56,Rear of 114,Asheland Ave.,Commercial,05/10/1960,Z. K. Morgan\nShirley P. Morgan\nJ. D. Medling...,Owner\n\n\n\n\n\nPurchaser,...,William J. Reeves\nMildred P. Reeves\n\nHACA,Owner\n\n\nPurchaser,04/12/1976,35000,-,-,-,-,-,03/30/1976
9,1,11,4,56,132 1/2,Asheland Ave.,Commercial,12/31/1968,"The Miller Printing Co. \n\nMillco, Incorporated",Owner\n\nPurchaser,...,"Millco, Incorporated\nM. O. Causey\n\nHACA",Owner\n\n\nPurchaser,09/01/1970\n03/31/1971,8000,-,-,-,-,-,09/03/1970
10,1,12,4,56,132,Asheland Ave.,Residential\nCommercial,05/12/1921\n\n07/11/1959,S.B Patterson\n\nHayward Powers\nJane Moore Po...,Owner\n\nOwner\n\n\nPurchaser,...,J. A. Reyes\n\nHACA,Owner\n\nPurchaser,03/26/1976,21500,-,-,-,-,-,03/30/1976
11,1,13,4,56,136,Asheland Ave.,Commercial,08/21/1961,Hayward Powers\nJane Moore Powers\n\nCharles M...,Owner\n\n\n\nPurchaser,...,Charles McGowan\n\nHACA,Owner\n\nPurchaser,-,-,-,-,-,-,-,08/30/1974
12,1,13A,4,56,136,Asheland Ave.,Commercial,08/22/1961,Hayward Powers\nJane Moore Powers\n\nCharles M...,Owner\n\n\n\nPurchaser,...,Charles McGowan\n\nHACA,Owner\n\nPurchaser,03/26/1976,800,-,-,-,-,-,03/30/1976
13,1,14,4,56,2,Wallack St.,Commercial\nResidential,01/06/1967,William P. Shuford\n\nJohn F. Shuford\nWachovi...,Owner\n\nHeir\nTrustees,...,John F. Shuford\nWachovia Bank and Trust Compa...,Owner\nTrustee\n\nPurchaser,-,-,-,-,-,Blaton A. Jones,Tenant,07/10/1969
14,1,15,4,56,5,Wallack St.,Commercial,11/07/1961,Dora Kilpatrick\nW.B. Kilpatrick\n\nRudolph Gay,Owner\n\nPurchaser,...,Rudolph Gay\n\nHACA,Owner\n\nPurchaser,-,-,-,-,-,-,-,01/23/1969
15,1,16,4,56,7,Wallack St.,Residential,10/26/1951,Cora J. Shuford\n\nMary McCorkle,Owner\n\nPurchaser,...,Raymond McCorkle\nMarie McCorkle\n\nHACA,Heirs\n\nPurchaser,08/12/1976,2250,-,-,-,-,-,08/17/1976
16,1,17,4,56,9,Wallack St.,Residential,05/11/1956,Guy Weaver\n\nAda J. Barnard,Owner\n\nPurchaser,...,Ada Barnard\n\nHACA,Owner\n\nPurchaser,1/2/1974,4000,-,-,-,-,-,01/07/1974
17,1,18,4,56,11,Wallack St.,Residential,01/11/1955,S.M. White\n\nHerman Fleming\nLaura Fleming,Owner\n\nPurchaser,...,Herman Fleming\n\nHACA,Owner \n\nPurchaser,-,-,-,-,-,-,-,03/23/1976
18,1,19,4,56,15,Wallack St.,Commercial,11/01/1966,W.R. Clements\nMary S. Clements\n\nGenuine Par...,Owner\n\nPurchaser,...,Genuine Parts Company\n\nHACA,Owner \n\nPurchaser,-,-,-,-,-,-,-,08/31/1970
19,1,20,4,56,17,Wallack St.,Commercial,12/03/1967,Hugh A. Messer\n\nMildred L. Messer,Owner\n\nPurchaser,...,Mildred L. Messer\n\nHACA,Owner \n\nPurchaser,-,-,-,-,-,L. Patton,Tenant,08/15/1969
20,1,21,4,56,23,Wallack St.,Commercial,12/20/1966,T. Carlisle Smith\n\nHilda B. Smith\nFirst Uni...,Owner\n\nHeir\nTrustees,...,Thomas F. Ruth\nAnne McConnel Ruth\n\nHACA,Owner \n\nPurchaser,-,-,-,-,-,-,-,03/19/1970
21,1,22,4,56,23,Wallack St.,Commercial,10/26/1949,W.P. Shuford\n\nEarnst Cannon\nParrylee Cannon,Owner\n\n\nPurchaser,...,Ruben J. Dailey\n(Administrator of the Estate ...,Trustee\n\n\n\nPurchaser,11/23/1976,4000,-,-,-,-,-,11/17/1976
22,1,24,4,56,55,Wallack St.,Commercial,08/15/1914\n\n06/13/1915,Thomas R. Tweed\n\nH.B. Ray\n\nJoseph Dodd\nGe...,Owner\n\n\nPurchaser,...,Josephine Beam\nAlfred Beam\n\nHACA,Owner \n\nPurchaser,03/31/1971\n09/19/0170,8000,-,-,-,-,-,09/03/1970
23,1,25,4,56,47 1/2,Wallack St.,Commercial,12/05/1938,R.E. Shuford\nMary Emma Shuford\n\nCora J. Shu...,Owner\n\n\nHeir,...,Cora J. Shuford\n\nHACA,Owner \n\nPurchaser,-,-,-,-,-,Willie B. Brownlee,Tenant,02/24/1969
24,1,27,4,56,77,Wallack St.,Residential,5/31/49,Jessie Pasley\n\nWillie Watson\nMamie Watson,Owner\n\nPurchaser,...,NaN,NaN,-,-,-,-,-,-,-,5/29/75
25,1,28,4,56,87,Wallack St.,Commercial,5/15/1899\n\n1/15/40,S. Hirsh\nAmelia Hirsh\n\nH. E. Thompson\n----...,Trustee\n\nPurchaser,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1,29,4,56,Rear of 87,Wallack St.,Commercial,11/14/21\n------------\n12/6/21,Mary Davis\n\nF. M. Stevens\n-----------------...,Owner\n\nPurchaser\n-------------\nOwner\n\nPu...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1,30,4,56,Rear of 102,Wallack St.,Commercial,6/14/1909,Robert b. Glenn\nJoanna Glenn\n\nLeah Clark,Owner\n\nPurchaser,...,Maizei Clark Williams\n\nHACA,Owner\n\nPurchaser,08/04/1970,1700,-,-,-,-,-,9/15/1970
28,1,31,4,56,102,Wallack St.,Residential,11/27/1946,Warren J. Clark\n\nMazie Williams,Owner\n\nPurchaser,...,Mazie Williams\n\nHACA,Owner\n\nPurchaser\n,-,-,-,-,-,-,-,4/3/69
29,1,32,4,56,101,Wallack St.,Commercial,8/3/50,John Powers\nMaggie Powers\nPauline Johnson\nB...,Heirs\n\nPurchaser,...,Etta Lynch\nPauline P. Hood\n\nHACA\n,Heirs\n\nPurchaser,3/10/75,750,-,-,-,-,-,3/21/75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,53,2,4,71,9,Across from 9 Louie St,Residential,5/22/1959,F.H. Harris and Jean Wesver Harris\n\nF.H. Har...,Owner \n\nPurchaser,...,-,-,5/31/1973,600,-,-,-,-,-,05/31/1973
526,50,18,4,71,N/S,N/E Cor. Southern St. \nand Graham Place,Residential,08/05/1907,Jacob Gilbert\nBetsy Gilbert\n\nW.E. Logan,Owner\n\n\nPurchaser,...,-,-,07/12/1973,450,-,-,-,-,-,07/24/1973
527,50,19,4,71,N/S,Southern Street,Residential,08/__/1927,Harry L. Nettles\nMargaret G. Nettles\n\nSouth...,Owner\n\n\nPurchaser,...,-,-,10/21/1973,350,-,-,-,-,-,10/26/1971
528,4,24,4,57,99,Asheland,Commercial,02/03/1962\n02/21/1962,Cordell Y. Jenkins\nMargaret M. Marjorie S. Je...,Owner\nPurchaser,...,Fred Pearlman\nAnne M. Pearlman\n\nHACA,Owner\n\n\nPurchaser,-,-,-,03/07/1969,40,Rev. Ben Jamison,Tenant,02/04/1969
529,4,23,4,57,105,Asheland,Commercial,03/08/1950,Clara Josephine Lee\nWilliam N. Lee\nWilla Mae...,Owner\n\n\n\nPurchaser,...,Roxie Holden Queen\nGleen Queen\n\nHACA,Owner\n\n\nPurchaser,-,-,-,-,-,-,-,10/14/1971
530,5,16,4,57,33,Silver Street,Residential,7/27/1944,Louis Gallego\nAgnes Gallego\n\n\nRoy Booker \...,Owner\n\n\n\n\nPurchaser,...,NaN,NaN,NaN,5450,12/20/1968,NaN,NaN,NaN,NaN,NaN
531,5,13,4,57,NaN,Near 176 S. Grove Rd,Residential,12/10/1959,Barney Brown\n\n\nElizabeth Whitson,Owner\n\n\nPurchaser,...,NaN,NaN,NaN,6250,NaN,NaN,NaN,NaN,NaN,NaN
532,5,12,4,57,178 1/2,S. Grove Road,Residential,8/9/1939,Home Owner's Loan Corp Of Washington D.C. \n\n...,Owner \n\nPurchaser,...,Marshall Logan\nGladys Logan\n\nHACA,Owner\n\n\nPurchaser,NaN,4300,-,-,-,-,-,12/8/1971
533,53,15B,4,71,493,S. French Broad Avenue,Residential,05/02/1955,R.D Burgin\n\nIra I. Angel\nLessie K. Angel,Owner\n\nPurchaser,...,Lessie K. Angel\n\nHACA,Owner\n\nPurchaser,-,-,-,-,-,-,-,04/26/1977
534,53,8,4,71,494-496,Depot Street,Residential,05/04/1937,Marie G. Wehry\n\nArthur A. York and Virginia ...,Owner\n\nPurchaser,...,VIrginia York\n\nHACA,Owner\n\nPurchaser,11/06/1968,8100,NaN,NaN,NaN,NaN,NaN,02/25/1970
535,55,40,4,72,113,Black Street,Residential,12/13/1954,Claudia Jenkins\n\nHenry Maddox\nManor Lee Maddox,Owner\n\nHeir,...,Henry Maddox\nManor Lee Maddox\n\nHACA,Owner\n\nPurchaser,NaN,NaN,NaN,07/25/1969,$10/month,Dock Maddox,Tenant,04/24/1969
536,55,41,4,72,103,Black Street,Church,02/17/1916,J. O. Whitted\nGertrude Whitted\n\nFire Baptis...,Owner\n\n\nPurchaser,...,Fire Baptized Holiness Church of God of the Am...,Owner\n\nPurchaser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/29/1970\n01/29/1970
537,5,6,4,57,168.5,South Grove Street,Residential,05/20/1941,Christine Ray\n\nW. M. Stowers\nNena Stowers,Owner\n\nPurchaser,...,NaN,NaN,05/22/1975,4600,NaN,NaN,NaN,NaN,NaN,06/06/1975
538,5,9,4,57,174,Rear of 174 South Grove Street,Residential,08/31/1956,Bismark Williams Jr.\nCoretta Williams\n\nBird...,Owner\n\n\nPurchaser,...,NaN,NaN,07/18/1975,6750,NaN,NaN,NaN,NaN,NaN,10/24/1975
539,5,10,4,57,174,Rear of 174 South Grove Street,Residential,09/05/1945,Anna Shuford Moore\nMeredith Moore\n\nJosh Col...,Owner\n\n\n\nPurchaser,...,Adeline Cole (formerly Cole)\n\nHACA,Owner\n\n\nPurchaser,09/19/1974,4500,NaN,NaN,NaN,NaN,NaN,10/14/1974
540,5,11,4,57,192,South Grove Street,Residential,12/03/1954,Stanton Golden\nBetty P. Golden\n\nErvin Gardn...,Owner\n\n\nPurchaser,...,Katherine Gardner\n\nRedevelopment Commission ...,Owner\n\nPurchaser,11/05/1969,5000,NaN,NaN,NaN,NaN,NaN,11/05/1969
541,4,6,4,57,NaN,NaN,Commercial,01/04/1966,"W. T. Duckworth, Jr., Homer W. Brooks\nThomas ...",Owner\n\n\n\n\nPurchaser,...,NaN,NaN,04/07/1976,4550,NaN,NaN,NaN,NaN,NaN,04/12/1976
542,4,9,4,57,118,South Grove Street,Residential,02/07/1964,Mamie Machen\n\nJames Edward King,Owner\n\nPurchaser,...,James Edward King\nPatricia Ann King\n\nRedeve...,Owner\n\nPurchaser,NaN,6000,NaN,NaN,NaN,NaN,NaN,12/11/1969
543,4,21,4,57,113,Asheland Ave.,Residential,12/13/1954,H.G. Cliff\n\nJulia Cliff Morris\nLouise Cliff...,Owner\n\nHeirs,...,Julia Cliff Morris\nW.K. Morris\nJack B. Cliff...,Owner\n\nPurchaser,-,-,-,-,-,-,-,07/08/1969
544,4,22,4,57,111,Asheland Ave.,Commercial,01/19/1965,First Union National Bank\nD. B. McKenzie\n\nJ...,Trustee\n\nOwner?\n\nPurchaser,...,Max E. Wilson\nFlora J. Wilson\n\nHACA,Owner\n\nPurchaser,04/07/1976\n04/23/1976,11300,-,-,-,-,-,04/12/1976
545,53,9,4,71,502,Depot St.,Residential,11/22/1960,H. E. Garrett\n\nCharles G. Buck\nNell P. Garrett,Owner\n\nTrustee,...,Charles G. Buck\nNell P. Garrett\n\nHACA,Trustee\n\nPurchaser,-,-,-,-,-,-,-,06/19/1969
546,55,1,4,71,82,Livingston St.,Residential,03/05/1965,Estelle B. Smith\n\nFred Barnette,Owner\n\nPurchaser,...,Fred Barnard\nRoselyn Barnard\n\nHACA,Owner\n\nPurchaser,-,-,-,-,-,-,-,05/08/1970
547,4,5,4,57,100,South Grove Street,Residential,9/25/1959,Marguerita W. Thompson\n\nW.T. Conley\nMary Lo...,Owner \n\nPurchaser,...,-,-,NaN,-,-,-,-,-,-,-
549,6,8,4,59,88,South French Broad Ave.,Residential,8/25/1945,E Zaph Ray\nMary Carr\n\nAugust J Erickson\nMa...,Owner\n\npurchaser,...,NaN,NaN,NaN,NaN,8/5/1969,-,-,NaN,NaN,7/17/1969
550,5,21,4,59,7,Silver St.,Residential,12/13/1960,Claude Marion Creasman\n\nMyrdirth Owen,owner\n\npurchaser,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/21/1972
551,5,21,4,59,7,Silver St.,Residential,12/13/1960,Claude Marion Creasman\n\nMyrdirth Owen,owner\n\npurchaser,...,Myrdirth Owen Howell\n\nHACA,owner\n\npurchaser,-,-,-,-,-,-,-,11/21/1972
552,5,21,4,59,7,Silver St.,Residential,12/13/1960,Claude Marion Creasman\n\nMyrdirth Owen,Owner \n\nPurchaser,...,Myrdirth Owen Howell\n\nHACA,Owner\n\npurchaser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/21/1972
553,6,38,4,59,8,DeWitt St.,Residential,11/13/1962,Sandra Olivia Nicholas\n\nZipporah L. Nicholas,Owner\n\nPurchaser,...,Zipporah Nicholas\n\nHACA,owner\n\npurchaser,4/1/1977,19750,NaN,NaN,NaN,NaN,NaN,7/28/1977
554,6,38,4,59,8,DeWitt St.,Residential,11/14/1962,Sandra Olivia Nicholas\n\nZipporah L. Nicholas,Owner\n\nPurchaser,...,Zipporah Nicholas\n\nHACA,owner\n\npurchaser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
555,6,38,4,59,8,DeWitt St.,Residential,11/14/1962,Sandra Olivia Nicholas\n\nZipporah L. Nicholas,Owner \n\nPurchaser,...,Zipporah Nicholas\n\nHACA,owner\n\npurchaser,06/07/1976,17150,-,-,-,-,-,NaN